### ISSUE TITLE
Enhancement for Communities

### ISSUE THREAD

**Issue by Seanman236** [ericrsmith35/Lightning-Components#2]
Been working with this in a Spring 19 sandbox and it's really cool - thanks for putting this out there!  We use a Lightning Community so I adjusted it to be visibile; however, I can't quite get it working the same way it works in an internal Lightning environement.

Use case - User is on an account record with the toggle component.  If flipped to true, the toggle updates a checkbox to reveal a list view component.  If flipped back to false, the list view is hidden.   When flipping the toggle, this checks a box which fires a flow to update a checkbox on the user's record (since communities use  audiences for component  visibility.  Everything works as expected and the refresh animation spins where the list view is.

But... the component visibility doesn't actually change after the closequickaction event fires.  I have to refresh the browser page manually to get it change.  

I adjusted the controller in a bunch of different ways to try a refreshView event but no dice.  The only Putting a navigatetoURL event before the closequickaction works as it opens an all new tab - which works - but isn't quite ideal.

   component.find("recordEditor").saveRecord($A.getCallback(function(saveResult){
            if(saveResult.state === "SUCCESS" || saveResult.state === "DRAFT"){
           	console.log("Save completed successfully.");  
       			var urlEvent = $A.get("e.force:navigateToURL");
        		urlEvent.setParams({ "url": component.get("v.recordId")});                   
    			urlEvent.fire();
   												 $A.get("e.force:closeQuickAction").fire();

Do you think this is just a limit within Communities?

Thanks again for putting this out there!!

**Comment by ericrsmith35** [comment]
I definitely think it is a Community issue.  I wish there was more compatibility there.

**Comment by ericrsmith35** [comment]
I just made a minor update to refresh the record before processing the field update.  See if it works for you now.
